services:
  postgres:
    image: postgres:15
    container_name: fib-postgres
    restart: always
    environment:
      POSTGRES_DB: fibdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fib-redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_CONNECTION_STRING=redis:6379  # Set your Redis connection string here
    depends_on:
      - redis
      - postgres
    ports:
      - "5000:80"  # Adjust this if needed

volumes:
  pgdata: