services:
  postgres:
    image: postgres:15
    container_name: fib-postgres
    restart: always
    environment:
      POSTGRES_DB: fibdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: fib-redis
    ports:
      - "6379:6379"

  grpc:
    build:
      context: ./Fibonacci.Calculator
      dockerfile: Dockerfile
    container_name: fib-grpc
    environment:
      - REDIS_CONNECTION_STRING=redis:6379
    depends_on:
      - redis
      - postgres
    ports:
      - "5000:80"

  bff:
    build:
      context: .
      dockerfile: FibonacciBFF/Dockerfile
    container_name: fib-bff
    depends_on:
      - grpc
    ports:
      - "5100:8080"

networks:
  default:
    name: fib-network

volumes:
  pgdata: